services:
  nginx:
    image: nginx:latest
    networks:
      - nginx.docker
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  
networks:
  nginx.docker:
    name: nginx.docker
    external: true