services:
  openproject:
    build: ./openproject
    hostname: openproject-app
    volumes:
      - ./openproject/pgdata:/var/openproject/pgdata
      - ./openproject/assets:/var/openproject/assets 
    ports:
      - 8080:8080
    networks:
      - default
      
  nginx_test:
    build: ./nginx
    ports:
      - 80:80
    networks:
      - nginx.docker
      - default

  # simple_log:
  #   build: ./nodejs
  #   hostname: nodeapp
  #   environment:
  #     - PORT=3001
  #   ports:
  #     - 3001:3001
    
networks:
  nginx.docker:
    name: nginx.docker
    external: true
  default:
